1	#时钟信号连接
2	set_property PACKAGE_PIN AC19 [get_ports clk]
3	
4	#脉冲开关，用于输入作为复位信号，低电平有效
5	set_property PACKAGE_PIN Y3 [get_ports resetn]
6	
7	#拨码开关连接，用于输入，依次为sw0,sw1
8	set_property PACKAGE_PIN Y6   [get_ports input_sel[0]]
9	set_property PACKAGE_PIN AD24 [get_ports input_sel[1]]
10	
11	set_property IOSTANDARD LVCMOS33 [get_ports clk]
12	set_property IOSTANDARD LVCMOS33 [get_ports resetn]
13	set_property IOSTANDARD LVCMOS33 [get_ports input_sel[1]]
14	set_property IOSTANDARD LVCMOS33 [get_ports input_sel[0]]
15	
16	#触摸屏引脚连接
17	set_property PACKAGE_PIN J25 [get_ports lcd_rst]
18	set_property PACKAGE_PIN H18 [get_ports lcd_cs]
19	set_property PACKAGE_PIN K16 [get_ports lcd_rs]
20	set_property PACKAGE_PIN L8 [get_ports lcd_wr]
21	set_property PACKAGE_PIN K8 [get_ports lcd_rd]
22	set_property PACKAGE_PIN J15 [get_ports lcd_bl_ctr]
23	set_property PACKAGE_PIN H9 [get_ports {lcd_data_io[0]}]
24	set_property PACKAGE_PIN K17 [get_ports {lcd_data_io[1]}]
25	set_property PACKAGE_PIN J20 [get_ports {lcd_data_io[2]}]
26	set_property PACKAGE_PIN M17 [get_ports {lcd_data_io[3]}]
27	set_property PACKAGE_PIN L17 [get_ports {lcd_data_io[4]}]
28	set_property PACKAGE_PIN L18 [get_ports {lcd_data_io[5]}]
29	set_property PACKAGE_PIN L15 [get_ports {lcd_data_io[6]}]
30	set_property PACKAGE_PIN M15 [get_ports {lcd_data_io[7]}]
31	set_property PACKAGE_PIN M16 [get_ports {lcd_data_io[8]}]
32	set_property PACKAGE_PIN L14 [get_ports {lcd_data_io[9]}]
33	set_property PACKAGE_PIN M14 [get_ports {lcd_data_io[10]}]
34	set_property PACKAGE_PIN F22 [get_ports {lcd_data_io[11]}]
35	set_property PACKAGE_PIN G22 [get_ports {lcd_data_io[12]}]
36	set_property PACKAGE_PIN G21 [get_ports {lcd_data_io[13]}]
37	set_property PACKAGE_PIN H24 [get_ports {lcd_data_io[14]}]
38	set_property PACKAGE_PIN J16 [get_ports {lcd_data_io[15]}]
39	set_property PACKAGE_PIN L19 [get_ports ct_int]
40	set_property PACKAGE_PIN J24 [get_ports ct_sda]
41	set_property PACKAGE_PIN H21 [get_ports ct_scl]
42	set_property PACKAGE_PIN G24 [get_ports ct_rstn]
43	
44	set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
45	set_property IOSTANDARD LVCMOS33 [get_ports lcd_cs]
46	set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
47	set_property IOSTANDARD LVCMOS33 [get_ports lcd_wr]
48	set_property IOSTANDARD LVCMOS33 [get_ports lcd_rd]
49	set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl_ctr]
50	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[0]}]
51	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[1]}]
52	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[2]}]
53	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[3]}]
54	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[4]}]
55	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[5]}]
56	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[6]}]
57	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[7]}]
58	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[8]}]
59	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[9]}]
60	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[10]}]
61	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[11]}]
62	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[12]}]
63	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[13]}]
64	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[14]}]
65	set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[15]}]
66	set_property IOSTANDARD LVCMOS33 [get_ports ct_int]
67	set_property IOSTANDARD LVCMOS33 [get_ports ct_sda]
68	set_property IOSTANDARD LVCMOS33 [get_ports ct_scl]
69	set_property IOSTANDARD LVCMOS33 [get_ports ct_rstn]
